# Download base image ubuntu 18.04
#FROM ubuntu:18.04
#
#ARG DEBIAN_FRONTEND=noninteractive
#
## Update Ubuntu Software repository
#RUN apt-get update

# Setup CRAN (R)
FROM r-base
# Example cran command: r -e "install.packages('fortunes', version = '1.5-4', repos = 'http://<server:port>/artifactory/<remote-repo-key>')"