FROM continuumio/miniconda:4.6.14

# Conda source in Artifactory: https://repo.continuum.io/pkgs/main/

# GNU Compiler Collection -> docker run --network=host <IMAGE-TAG> conda install --override-channels --channel http://<SERVER>/artifactory/api/conda/<REMOTE-REPO> libgfortran-ng